# Non Graded Challenge 5

_Non-Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program khususnya pada konsep Linear Algebra._

---

## Assignment Instructions

- Periksa apakah w = (-4, 5, 4) merupakan kombinasi linear dari v1 = (2, 1, 0) dan v2 = (=1, 3, 2)
- Misalkan V dan W adalah ruang vektor. Jika $T:\ V\rightarrow W$ adalah transformasi linear dan $u\in V$, maka buktikan bahwa $T(-u) = -T(u)$.

## Assignment Submission

- Simpan assignment pada sesi ini dengan nama `h8dsft_Linear_Algebra2`.
- Push Assigment yang telah kalian buat ke akun Github kalian masing-masing.

## Assignment Objectives

Non-Graded Assignment ini dibuat guna mengevaluasi konsep Linear Algebra sebagai berikut:

- Mampu memahami konsep linear transformation dan implementasinya
- Mampu memahami konsep linear combination dan implementasinya

- Periksa apakah w = (-4, 5, 4) merupakan kombinasi linear dari v1 = (2, 1, 0) dan v2 = (=1, 3, 2)
- Misalkan V dan W adalah ruang vektor. Jika $T:\ V\rightarrow W$ adalah transformasi linear dan $u\in V$, maka buktikan bahwa $T(-u) = -T(u)$.

#### Library yang digunakan

In [2]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import inv

### Problems

Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

In [4]:
# Melakukan Tensor 4D
v3 = np.array(

[[[[23,50],[7,12]],
[[57,67],[99,43]]],

[[[75,21],[57,12]],
[[87,26],[18,84]]]] )

print(v3)

[[[[23 50]
   [ 7 12]]

  [[57 67]
   [99 43]]]


 [[[75 21]
   [57 12]]

  [[87 26]
   [18 84]]]]


Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix},
  B = 
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

In [6]:
# Melakukan Perkalian matriks
A = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]])

b = np.array([17,22,19])

R = A.dot(b)
print(R)

[1852 2454 4305]


Lakukan Transpose, hitung Determinan, dan Inverse terhadap matrix dibawah :

$$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$

In [7]:
# Melakukan declare matriks
A = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]])

print(A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [8]:
# Determinan A
AD = det(A)
print(AD)

131344.0000000002


In [9]:
# Invers A
AI = inv(A)
print(AI)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
